language: scala

scala:
  - 2.11.12
  - 2.12.8

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

before_cache:
  - rm -f $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.sbt -name "*.lock" -type f -delete
cache:
  directories:
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt
