language: scala

scala:
  - 2.12.10
  - 2.13.1

jdk:
  - openjdk8

env:
  - TARGET=JVM
  - TARGET=JS
  - SCALAJS_VERSION=1.0.0-RC2 TARGET=JVM
  - SCALAJS_VERSION=1.0.0-RC2 TARGET=JS

script:
  - sbt ++$TRAVIS_SCALA_VERSION ${TARGET}/test

before_cache:
  - rm -f $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.sbt -name "*.lock" -type f -delete
cache:
  directories:
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt
